<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BT_2FSDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BT.2FSD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BT.2FSD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'equipe' => ['privates', '.errored..service_locator.BT.2FSD.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.BT.2FSD": it needs an instance of "App\\Entity\\Equipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'equipe' => 'App\\Entity\\Equipe',
        ]);
    }
}
