<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGeK4iVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QGeK4iV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QGeK4iV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entrainment' => ['privates', '.errored..service_locator.QGeK4iV.App\\Entity\\Entrainment', NULL, 'Cannot autowire service ".service_locator.QGeK4iV": it needs an instance of "App\\Entity\\Entrainment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entrainment' => 'App\\Entity\\Entrainment',
        ]);
    }
}
