<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ShdiLFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.shdiL_f' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.shdiL_f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournoi' => ['privates', '.errored..service_locator.shdiL_f.App\\Entity\\Tournois', NULL, 'Cannot autowire service ".service_locator.shdiL_f": it needs an instance of "App\\Entity\\Tournois" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournoi' => 'App\\Entity\\Tournois',
        ]);
    }
}
