<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7RLa5PTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7RLa5PT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7RLa5PT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'equipe' => ['privates', '.errored..service_locator.7RLa5PT.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.7RLa5PT": it needs an instance of "App\\Entity\\Equipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'equipe' => 'App\\Entity\\Equipe',
        ]);
    }
}
