<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WZk6Oc4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wZk6Oc4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wZk6Oc4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossiermedical' => ['privates', '.errored..service_locator.wZk6Oc4.App\\Entity\\Dossiermedical', NULL, 'Cannot autowire service ".service_locator.wZk6Oc4": it needs an instance of "App\\Entity\\Dossiermedical" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dossiermedical' => 'App\\Entity\\Dossiermedical',
            'entityManager' => '?',
        ]);
    }
}
