<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E4Fd3DeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e4Fd3De' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e4Fd3De'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'installationsportive' => ['privates', '.errored..service_locator.e4Fd3De.App\\Entity\\Installationsportive', NULL, 'Cannot autowire service ".service_locator.e4Fd3De": it needs an instance of "App\\Entity\\Installationsportive" but this type has been excluded in "config/services.yaml".'],
        ], [
            'installationsportive' => 'App\\Entity\\Installationsportive',
        ]);
    }
}
