<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IVBs8OkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iVBs8Ok' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iVBs8Ok'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'performanceathlete' => ['privates', '.errored..service_locator.iVBs8Ok.App\\Entity\\Performanceathlete', NULL, 'Cannot autowire service ".service_locator.iVBs8Ok": it needs an instance of "App\\Entity\\Performanceathlete" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'performanceathlete' => 'App\\Entity\\Performanceathlete',
        ]);
    }
}
