<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntrainmentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QGeK4iV.App\Entity\Entrainment' shared service.
     *
     * @return \App\Entity\Entrainment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QGeK4iV": it needs an instance of "App\\Entity\\Entrainment" but this type has been excluded in "config/services.yaml".');
    }
}
