<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchsportifService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1k.ko1J.App\Entity\Matchsportif' shared service.
     *
     * @return \App\Entity\Matchsportif
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1k.ko1J": it needs an instance of "App\\Entity\\Matchsportif" but this type has been excluded in "config/services.yaml".');
    }
}
