<?php

namespace ContainerB6tUEXr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournois2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.shdiL_f.App\Entity\Tournois' shared service.
     *
     * @return \App\Entity\Tournois
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.shdiL_f": it needs an instance of "App\\Entity\\Tournois" but this type has been excluded in "config/services.yaml".');
    }
}
