<?php

namespace Container8kUpjPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kwbt3LGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kwbt3LG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kwbt3LG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'performanceequipe' => ['privates', '.errored..service_locator.kwbt3LG.App\\Entity\\Performanceequipe', NULL, 'Cannot autowire service ".service_locator.kwbt3LG": it needs an instance of "App\\Entity\\Performanceequipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'performanceequipe' => 'App\\Entity\\Performanceequipe',
        ]);
    }
}
