<?php

namespace Container8kUpjPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ANruSuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ANruSu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ANruSu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'performanceequipe' => ['privates', '.errored..service_locator.6ANruSu.App\\Entity\\Performanceequipe', NULL, 'Cannot autowire service ".service_locator.6ANruSu": it needs an instance of "App\\Entity\\Performanceequipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'performanceequipe' => 'App\\Entity\\Performanceequipe',
        ]);
    }
}
