<?php

namespace Container8kUpjPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MNLi9uhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MNLi9uh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MNLi9uh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'performanceathlete' => ['privates', '.errored..service_locator.MNLi9uh.App\\Entity\\Performanceathlete', NULL, 'Cannot autowire service ".service_locator.MNLi9uh": it needs an instance of "App\\Entity\\Performanceathlete" but this type has been excluded in "config/services.yaml".'],
        ], [
            'performanceathlete' => 'App\\Entity\\Performanceathlete',
        ]);
    }
}
