<?php

namespace Container8kUpjPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ro1xyxmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ro1xyxm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ro1xyxm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matchsportif' => ['privates', '.errored..service_locator.ro1xyxm.App\\Entity\\Matchsportif', NULL, 'Cannot autowire service ".service_locator.ro1xyxm": it needs an instance of "App\\Entity\\Matchsportif" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matchsportif' => 'App\\Entity\\Matchsportif',
        ]);
    }
}
