<?php

namespace Container8kUpjPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlessure2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Dd86luN.App\Entity\Blessure' shared service.
     *
     * @return \App\Entity\Blessure
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Dd86luN": it needs an instance of "App\\Entity\\Blessure" but this type has been excluded in "config/services.yaml".');
    }
}
