<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'birthday' => [parent::class, 'birthday', null],
        "\0".parent::class."\0".'dossiermedicals' => [parent::class, 'dossiermedicals', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'equipe_id' => [parent::class, 'equipe_id', null],
        "\0".parent::class."\0".'equipes' => [parent::class, 'equipes', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image_url' => [parent::class, 'image_url', null],
        "\0".parent::class."\0".'mdp_hash' => [parent::class, 'mdp_hash', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'performanceathletes' => [parent::class, 'performanceathletes', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'tel' => [parent::class, 'tel', null],
        'adresse' => [parent::class, 'adresse', null],
        'birthday' => [parent::class, 'birthday', null],
        'dossiermedicals' => [parent::class, 'dossiermedicals', null],
        'email' => [parent::class, 'email', null],
        'equipe_id' => [parent::class, 'equipe_id', null],
        'equipes' => [parent::class, 'equipes', null],
        'id' => [parent::class, 'id', null],
        'image_url' => [parent::class, 'image_url', null],
        'mdp_hash' => [parent::class, 'mdp_hash', null],
        'nom' => [parent::class, 'nom', null],
        'performanceathletes' => [parent::class, 'performanceathletes', null],
        'prenom' => [parent::class, 'prenom', null],
        'role' => [parent::class, 'role', null],
        'status' => [parent::class, 'status', null],
        'tel' => [parent::class, 'tel', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
