<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipe extends \App\Entity\Equipe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coach_id' => [parent::class, 'coach_id', null],
        "\0".parent::class."\0".'division' => [parent::class, 'division', null],
        "\0".parent::class."\0".'entrainments' => [parent::class, 'entrainments', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'matchsportifsEquipe1' => [parent::class, 'matchsportifsEquipe1', null],
        "\0".parent::class."\0".'matchsportifsEquipe2' => [parent::class, 'matchsportifsEquipe2', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'performanceequipes' => [parent::class, 'performanceequipes', null],
        "\0".parent::class."\0".'sport' => [parent::class, 'sport', null],
        "\0".parent::class."\0".'utilisateurs' => [parent::class, 'utilisateurs', null],
        'coach_id' => [parent::class, 'coach_id', null],
        'division' => [parent::class, 'division', null],
        'entrainments' => [parent::class, 'entrainments', null],
        'id' => [parent::class, 'id', null],
        'matchsportifsEquipe1' => [parent::class, 'matchsportifsEquipe1', null],
        'matchsportifsEquipe2' => [parent::class, 'matchsportifsEquipe2', null],
        'nom' => [parent::class, 'nom', null],
        'performanceequipes' => [parent::class, 'performanceequipes', null],
        'sport' => [parent::class, 'sport', null],
        'utilisateurs' => [parent::class, 'utilisateurs', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
