<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tournois extends \App\Entity\Tournois implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'matchsportifs' => [parent::class, 'matchsportifs', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'performanceequipes' => [parent::class, 'performanceequipes', null],
        "\0".parent::class."\0".'sport' => [parent::class, 'sport', null],
        'adresse' => [parent::class, 'adresse', null],
        'dateDebut' => [parent::class, 'dateDebut', null],
        'dateFin' => [parent::class, 'dateFin', null],
        'id' => [parent::class, 'id', null],
        'matchsportifs' => [parent::class, 'matchsportifs', null],
        'nom' => [parent::class, 'nom', null],
        'performanceequipes' => [parent::class, 'performanceequipes', null],
        'sport' => [parent::class, 'sport', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
