<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8kUpjPD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8kUpjPD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8kUpjPD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8kUpjPD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8kUpjPD\App_KernelDevDebugContainer([
    'container.build_hash' => '8kUpjPD',
    'container.build_id' => '1c258f0f',
    'container.build_time' => 1743031444,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8kUpjPD');
