<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU9uRxQ9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU9uRxQ9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU9uRxQ9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU9uRxQ9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU9uRxQ9\App_KernelDevDebugContainer([
    'container.build_hash' => 'U9uRxQ9',
    'container.build_id' => 'db451b42',
    'container.build_time' => 1743116793,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU9uRxQ9');
